apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres-pod
    app: voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: voting-app