apiVersion: v1
kind: Pod
metadata:
  name: redis-app
  labels:
    name: redis-app-pod
    app: voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379