apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    name: result-app-pod
    app: voting-app
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80