apiVersion: v1
kind: Pod
metadata:
  name: vote-app
  labels:
    name: vote-app-pod
    app: voting-app
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80