apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    name: worker-app-pod
    app: voting-app
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
      ports:
        - containerPort: 80